val3_driver: Updated repo URL within README
ros-industrial/staubli_experimental pull request #17
Opened 2016-11-14 08:07 UTC by MuriloMartins

This PR addresses issue #13.

2016-11-14 08:45 UTC, gavanderhoorn requested changes
Minor change needed, otherwise +1.

2016-11-14 08:45 UTC, gavanderhoorn commented on staubli_val3_driver/README.md
> +git clone https://github.com/ros-industrial/staubli_experimental -b val3_server-devel
Shouldn't users clone just `indigo-devel`? Afaik there is no `val3_server-devel` branch on `ros-industrial/staubli_experimental`?

And as `indigo-devel` is the default, I think we can just omit the branch entirely.

2016-11-14 12:11 UTC, MuriloMartins commented on staubli_val3_driver/README.md
> +git clone https://github.com/ros-industrial/staubli_experimental -b val3_server-devel
I missed that... done.

2016-11-14 16:48 UTC, gavanderhoorn commented on staubli_val3_driver/README.md
> +Clone branch `val3_server-devel` of [staubli_experimental](https://github.com/ros-industrial/staubli_experimental):
I think you missed this one :)

2016-11-14 16:50 UTC, gavanderhoorn commented
Btw: the readme also directs users to:

> [..] copy the contents of `val3_driver` folder [..]

But that folder doesn't exist.

Should that be `val3`? Or would you want them to copy the `ros_libs` and `ros_server` directories separately?

2016-11-15 08:10 UTC, MuriloMartins commented
Oh, I seem to remember to have named that folder as `val3_driver`. I didn't realise that it had been renamed...

2016-11-15 08:14 UTC, gavanderhoorn commented
@MuriloMartins wrote:
> Oh, I seem to remember to have named that folder as `val3_driver`. I didn't realise that it had been renamed...

ah, right. Yes, I did that (when cleaning up the commits in #10) to get `staubli_val3_driver` more in-line with the other driver packages (ie: `fanuc_driver/karel`, `abb_driver/rapid`, etc). The directory already lives in a package with `driver` in it, so seems redundant to suffix it again.

2016-11-15 08:15 UTC, MuriloMartins commented
Just a sec, I'm working on it! ;-)

2016-11-15 08:16 UTC, gavanderhoorn commented
https://github.com/ros-industrial/staubli_experimental/pull/10#issuecomment-231539601 explains what happened :).

2016-11-15 08:19 UTC, MuriloMartins commented
Yes I remember now! Thanks!

I've just updated the readme with the correct branch (`indigo-devel`) and folder (`val3`) names.

2016-11-15 08:21 UTC, gavanderhoorn approved these changes

2016-11-15 08:22 UTC, gavanderhoorn commented
Thanks for the updates.

I'm going to squash-merge this.

2016-11-15 08:22 UTC, merged