Tx60 inclusion
ros-industrial/staubli_experimental pull request #19
Opened 2018-03-13 17:58 UTC by nilsmelchert

Requesting to add the packages `staubli_tx60_support` and `staubli_tx60_gazebo` the the `staubli_experimental` repository.

2018-03-17 13:05 UTC, gavanderhoorn requested changes
Overall: thanks for this PR, much appreciated.

Some minor things to change (see comments) and I noticed some issues with the meshes:

 - I have the impression that the normals of the collision meshes are not consistently pointing outwards. Can you load them in Meshlab (fi) and check? If you see black faces, that would confirm there is something wrong. You could also start `test_tx60.launch` and turn off the normal visual model and only enable visualisation of the collision model. If you see holes in the robot, the normals need fixing.
 - does `link_3.stl` contain two links in one file?

Furthermore: it would be great if we can try to reduce the size of the PR by making both variants share as many meshes as possible. Looking at the datasheet it seems like `base_link`, `link_1`, `link_3`, `link_5` and `link_6` could be identical. If you could check that and if they are, then I suggest we store those files once in the `tx60` folder, store the longer `link_2` and `link_4` in the `tx60l` folder and then make the TX60L xacro macro use the shared meshes from the `tx60` folder.

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_gazebo/launch/load_tx60.launch
> +  <param name="robot_description" command="$(find xacro)/xacro.py '$(find staubli_tx60_gazebo)/urdf/tx60.xacro'" />
Please change this to `xacro --inorder` (remove `.py`, add `--inorder`).

Same for the L launch file.

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_gazebo/package.xml
> +      model and the TX60.
Shouldn't this be "the base model and the L"?

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_gazebo/package.xml
> +  <author email="nils.melchert@imr.uni-hannover.de">Murilo Martins (Ocado Technology)</author>
I don't think you're Murilo.

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_gazebo/package.xml
> +  <run_depend>ros_controllers</run_depend>
I know this is a copy of the TX90 files, but please:

 - sort alphabetically
 - replace the dependency on `ros_controllers` (a metapackage) with the actual packages that this depends on. Probably `joint_state_controller` (already listed) and `joint_trajectory_controller` (also already listed).

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/CMakeLists.txt
> +  roslaunch_add_file_check(tests/roslaunch_test.xml)
You probably didn't notice this because there seems to be an issue with the Travis configuration, but your test files are actually called `test_tx60.launch` and `test_tx60l.launch`.

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/launch/load_tx60.launch
> +  <param name="robot_description" command="$(find xacro)/xacro.py --inorder '$(find staubli_tx60_support)/urdf/tx60.xacro'" />
Please remove the `.py` extension (same for L file).

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/package.xml
> +      as well a model with extended arm and forearm links.
Again a copy of the TX90 files, but please change to: "This includes the TX60 and the TX60L" (more explicit).

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/package.xml
> +      -Torque Limits- of the instruction manual for details).
Are these numbers correct for the TX60 (this text is identical to the TX90 manifest).

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/package.xml
> +    </p>
Please remove: you are already listed as the `author`, so we know this.

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_gazebo/package.xml
> +</package>
Please add:

```xml
<export>
  <architecture_independent />
</export>
```

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/tests/roslaunch_test.xml
> +</launch>
Please split this into two files, one for each variant (and update the `CMakeLists.txt`).

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/urdf/tx60.xacro
> +
Remove empty line.

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/urdf/tx60_macro.xacro
> +<inertial>
Indentation seems off here (same below).

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/urdf/tx60_macro.xacro
> +      <limit lower="${radians(-180)}" upper="${radians(180)}" effort="0.0" velocity="${radians(435)}" />
`effort` is set to `0.0` here: is that correct (same below)?

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/urdf/tx60_macro.xacro
> +      <origin xyz="0 0.02 0.290" rpy="0 0 0"/>
This will work, but we typically try to avoid having translations over more than one axis. The [datasheet](https://www.staubli.com/de-de/file/5285.show) that you linked in #18 also doesn't show both x and z translations for the third joint. Can you verify this and correct?

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/urdf/tx60_macro.xacro
> +      <origin xyz="0 0 0" rpy="0 0 0"/>
This is just a question (as I don't remember): is Staübli's `world` frame coincident with the actual base of the robot (so does it lie under the physical base of the it)? If not, this would have to be corrected.

2018-03-17 13:05 UTC, gavanderhoorn commented on staubli_tx60_support/urdf/tx60l.xacro
> +
Empty line.

2018-03-19 07:28 UTC, nilsmelchert commented on staubli_tx60_gazebo/package.xml
> +</package>
Should this be added right underneath the 'run-depend' tags?

2018-03-19 08:18 UTC, nilsmelchert commented on staubli_tx60_support/urdf/tx60_macro.xacro
> +      <origin xyz="0 0 0" rpy="0 0 0"/>
I corrected the location of 'base'. 
Is it correct, that 'base' is a child of 'base_link' or do Í have to correct that too?

2018-03-19 08:26 UTC, gavanderhoorn commented on staubli_tx60_gazebo/package.xml
> +</package>
Yes, that is ok. See [the manifest](https://github.com/ros-industrial/staubli_experimental/blob/edfb85f6303c880098d86261d14f442156c4c03c/staubli_tx90_support/package.xml#L67-L70) of `staubli_tx90_support`.

2018-03-19 08:28 UTC, gavanderhoorn commented on staubli_tx60_support/urdf/tx60_macro.xacro
> +      <origin xyz="0 0 0" rpy="0 0 0"/>
`base` can be a child of `base_link`, yes. It just depends on what the most convenient parent is.

A lot of robots have their world origin at the intersection of `J1` and `J2`, but `link_1` can't be used in those cases, as the world frame would then rotate whenever `link_1` is rotated. So `base_link` is the next logical choice.

2018-03-19 14:43 UTC, nilsmelchert commented
> does link_3.stl contain two links in one file?

`link_3.stl` looks fine to me for both versions of the robots. It looks a bit different from the TX90 series. Or did I miss out on something?

2018-03-19 14:48 UTC, gavanderhoorn commented
@nilsmelchert wrote:
> @gavanderhoorn:
> > does link_3.stl contain two links in one file?
> 
> `link_3.stl` looks fine to me for both versions of the robots. It looks a bit different from the TX90 series. Or did I miss out on something?

You're right. The 'strange' shape confused me.

2018-03-19 15:28 UTC, nilsmelchert commented on staubli_tx60_gazebo/package.xml
> +</package>
Shouldn't  `<architecture_independent />` then rather be added to  `staubli_tx60_support/package.xml` instead  of `staubli_tx60_gazebo/package.xml`?

2018-03-19 15:35 UTC, gavanderhoorn commented on staubli_tx60_gazebo/package.xml
> +</package>
It should be added to all the packages you contributed, as none of them include any compiled artefacts.

2018-03-19 15:37 UTC, gavanderhoorn commented
Your last commit does not appear to be made using a client that had your registered email address configured. That is fine, but will mean that the commit won't be attributed to your account.

2018-03-19 15:40 UTC, nilsmelchert commented
I included every change that was requested. Please have a closer look at the new frames in the urdf files. There is not only `one translation` per joint. In my opinion, the frames look kind of strange, but regarding the [official datasheet](https://www.staubli.com/en-de/file/5285.show), it seems to be the only way to fullfill the desired criteria of only `one translation` per joint. 
Thanks for your work!

2018-03-19 15:41 UTC, nilsmelchert commented
> Your last commit does not appear to be made using a client that had your registered email address configured. That is fine, but will mean that the commit won't be attributed to your account.

How can I change that?

2018-03-19 15:44 UTC, gavanderhoorn commented
You can either register your other email address with github (as a second one for your current account), or you could do something like:

```
git commit --amend --author "Your Name <correct@email.address>" --no-edit
```

and then a `git push $name_of_remote tx60_inclusion --force`.

That will overwrite your last commit to the `tx60_inclusion` branch.

Be sure to check that everything is ok before you do that though. You can do that with `git log -n1` or `gitk`.

2018-03-19 15:59 UTC, nilsmelchert commented
> Your last commit does not appear to be made using a client that had your registered email address configured. That is fine, but will mean that the commit won't be attributed to your account.

I did a small commit to update my email address. Thanks for the review.

2018-03-20 18:50 UTC, gavanderhoorn commented
I've added a few more commits to tidy up some things.

I've reverted the changes to the mesh and `joint` origins that you made in 87f728d: looking at the datasheet you linked allowing the small `y` translation for `joint_2` makes more sense than to have the entire `link_2` to `link_4` subtree run 'outside' the robot.

I've also removed your email address from the `author` tag in the manifest of `tx60_gazebo` (in 6ef9dab): it's more consistent with `tx60_support` this way. If you want to have your email address in both that's fine with me. Just be prepared to receive emails from the buildfarm if there are ever any issues with any builds.

2018-03-20 18:50 UTC, gavanderhoorn commented
Other than that this is quite excellent work @nilsmelchert. Thanks for the PR and the contribution.

2018-03-20 19:02 UTC, gavanderhoorn commented
One thing I noticed is that the xacros claim that `link_6` weighs only 8 grams, which seems a bit on the low side, but we've added a disclaimer to the package manifest, so users should be aware.

2018-03-20 20:14 UTC, nilsmelchert commented
> I've also removed your email address from the author tag in the manifest of tx60_gazebo

That's fine with me.

2018-03-20 20:17 UTC, nilsmelchert commented
> One thing I noticed is that the xacros claim that link_6 weighs only 8 grams, which seems a bit on the low side, but we've added a disclaimer to the package manifest, so users should be aware.

That is because of the assumption of a homogeneously distributed density with was made in the `stable_tx90_support` package. The weights and inertias are definitely still not accurate. But as soon as I get the sytem identification done, I will contribute my results.

2018-03-20 20:19 UTC, nilsmelchert commented
> Other than that this is quite excellent work @nilsmelchert. Thanks for the PR and the contribution.

Very welcome. I am still new to ROS and even git. But I am sure that this was not my last contribution.

2018-03-20 20:21 UTC, nilsmelchert commented
> I've added a few more commits to tidy up some things.

So do I have to make some more changes on my PR? How are you able to make commits? 
Let me know, if I can do something to finish the `addition of the tx60 series`.

2018-03-20 20:27 UTC, gavanderhoorn commented
@nilsmelchert wrote:
> > I've added a few more commits to tidy up some things.
> 
> So do I have to make some more changes on my PR?

No.

> How are you able to make commits? 

Because by default, PRs on github have [allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) enabled.

> I mean if you reverted the changes, the collision models also have to be adjusted again. I could definitely do that, if that still needs to be done.

I updated the collision meshes as well.

2018-03-20 20:27 UTC, gavanderhoorn commented
I was just waiting for Travis to complete.

2018-03-20 20:29 UTC, gavanderhoorn approved these changes
This is ok now.

Any further issues we / you discover can be fixed in future PRs.

2018-03-20 20:30 UTC, merged

2018-03-20 20:30 UTC, nilsmelchert commented
Ok so I guess my work is done here.

Thanks a lot for your help and reviews. I learned a lot and I am also very thankful for people like you, who make my research so much easier.

2018-03-20 20:31 UTC, gavanderhoorn commented
Thanks again @nilsmelchert :+1:

2018-03-20 20:31 UTC, gavanderhoorn commented
No problem.

I look forward to the results of your system identification.

2018-03-20 20:39 UTC, gavanderhoorn commented
Note that I did a `squash and merge` when merging your PR. It may look like those commits have not been merged, and that would be correct: to avoid all the fixup commits to become part of the history of this repository I've squashed them into a single one (e3a983c) and merged that.

Your `tx60_inclusion` branch will still show all those individual commits, but `indigo-devel` should not (if you update it from this repository).

2018-03-20 20:44 UTC, nilsmelchert commented
>  I've squashed them into a single one (e3a983c) and merged that.

Ok good. One more thing I learned about git ;-)